name: CI/CD Pipeline Innovatech

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código en GitHub
        uses: actions/checkout@v3

      - name: 2. Copiar los archivos a la máquina EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/innovatech-app"

      - name: 3. Ejecutar Docker Compose en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/innovatech-app
            docker-compose up -d --build
